### ISSUE TITLE
Suggestion for date object returned by toUTC

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/tz.js#2]
I see that toUTC returns an object. I find this preferable to the way other libraries do it because then I can build out the format I need. However, I don't have all the pieces I really want.

Would it be better for the object to contain all the formats of the various date parts according to the unicode symbols? Intl.DateTimeFormat().resolvedOptions().timeZone;

**Comment by coolaj86** [comment]
Can you give some more concrete examples?

**Comment by ryanburnette** [comment]
Sure.

My thought is that while the resulting object is somewhat unique to this library, the attributes of the object could follow Unicode date patterns used by most other libraries one would encounter when dealing with dates.

I usually use date-fns, for example, and would format a date object like this.

```js
formatDate(new Date(), 'MM dd, YYYY');
```

If your library generated an object with attributes that adhered to Unicode date patterns, you could do the same thing. Example:

```js
// fake object with a few example attributes
var obj = {
  MM: 'March',
  dd: '3',
  YYYY: '2022'
};

var formattedDate = `${obj.MM} ${obj.dd}, ${obj.YYYY}`;
```

Having the ability to turn a date into an object like this is much more convenient than including date-fns and I'd use such a library all the time.

I must add a disclaimer that my understanding on this topic is limited to usage in my projects, and I am well aware that you really don't know a part of the stack until you get to a point where you could write or have written that part of the stack. Thanks for reading.

**Comment by coolaj86** [comment]
I don't think it's a bad idea, but I don't think it's useful enough over the current structure to warrant an API change.

```json5
{
  // date
  "year": 2021, "month": 2, "day": 14,
  // time
  "hour": 3, "minute": 15, "second": 59, "millisecond": 0,
  // tz
  "offset": -240, "timeZoneName": "Eastern Daylight Time"
}
```
